### ISSUE TITLE
README.md 빌드 설명추가

### ISSUE THREAD

**Issue by hunecenter94** [eGovFramework/egovframe-simple-homepage-template#10]
해당 프로젝트에 대한 설명이 없어서 빌드 방법을 README.md에 설명을 추가해주시면 좋을거같습니다.

[simple-homepage-template]을 빌드해서 띄워보고 싶어도 설명이 없어서 아쉽습니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에 
대단히 감사드립니다.
